#!/bin/sh

setup-interfaces
rc-service networking -q start &
doas rc-update add networking boot
echo-e "http://dl-cdn.alpinelinux.org/alpine/edge/main\n http://dl-cdn.alpinelinux.org/alpine/edge/community" > /etc/apk/repositories
apk update && apk upgrade 
apk add lsblk efibootmgr grub-efi 
BOOTLOADER=grub
USE_EFI=1
mkdir -p /mnt/home
mkdir -p /mnt/boot/efi
mount /dev/nvme0n1p1 /mnt/boot/efi
mount /dev/nvme0n1p6 /mnt
mount /dev/nvme0n1p7 /mnt/home
setup-disk /mnt
setup-devd udev


apk add brightnessctl cfdisk curl dbus e2fsprogs efibootmgr firefox foot gcc git grim grub-efi \
    hwdata hwdata-dev iwd jpeg-dev lf libliftoff-dev libnotify linux-firmware-amdgpu lsblk make \
    mako mandoc mesa-dri-gallium mkinitfs mpv musl-dev ncdu ncurses-dev neovim openssh pass patch \
    pciutils pipewire-pulse pipewire-tools seatd slurp socat tllist-dev wf-recorder wlroots-dev \
    wl-clipboard wpa_supplicant xdg-desktop-portal-wlr

doas rc-update add sshd
doas rc-update add seatd
doas rc-update add brightnessctl
doas rc-service seatd start
doas rc-service sshd start
adduser night
addgroup night wheel; addgroup night input; addgroup night seat; addgroup night video;
cat > /etc/ssh/sshd_confi << EOF
Include /etc/ssh/sshd_config.d/*.conf
Port 44114
AuthorizedKeysFile	.ssh/authorized_keys
PasswordAuthentication no
PermitEmptyPasswords no
AllowTcpForwarding no
GatewayPorts no
X11Forwarding no
EOF

echo -e "amdgpu\nfbcon\nnouveau" >> /etc/modules
echo -e "permit persist :wheel\npermit nopass :wheel\npermit nopass night as root" >> /etc/doas.d/doas.conf
