#!/bin/sh

setup-interfaces
rc-service networking -q start &
rc-update add networking boot
echo-e "http://dl-cdn.alpinelinux.org/alpine/edge/main\nhttp://dl-cdn.alpinelinux.org/alpine/edge/community" > /etc/apk/repositories
apk update && apk upgrade 
apk add lsblk efibootmgr grub-efi 
BOOTLOADER=grub;USE_EFI=1
mkdir -p /mnt/home
mkdir -p /mnt/boot/efi
mount /dev/nvme0n1p1 /mnt/boot/efi
mount /dev/nvme0n1p6 /mnt
mount /dev/nvme0n1p7 /mnt/home
setup-disk /mnt

setup-devd udev
apk add acpid brightnessctl curl dbus e2fsprogs efibootmgr firefox fnf foot \
    gcc git grim groff grub-efi hwdata-dev imagemagick jpeg-dev lf \
    libliftoff-dev libnotify linux-firmware-amdgpu lsblk make mako mandoc \
    mesa-dri-gallium mkinitfs mpv musl-dev ncdu ncurses ncurses-dev neovim \
    openssh pass patch pciutils pipewire-pulse pipewire-tools scdoc seatd \
    slurp socat stagit tllist-dev wbg wf-recorder wlroots-dev wl-clipboard wmenu \
    wpa_supplicant xdg-desktop-portal-wlr zzz

rc-update add sshd
rc-update add seatd
rc-update add brightnessctl
rc-update add acpid
rc-update add iwd
rc-service seatd start
rc-service sshd start
rc-service iwd start
rc acpid start
USERNAME=night; setup-user -a -f Night -g wheel,input,seat,video
cat > /etc/ssh/sshd_config << EOF
Include /etc/ssh/sshd_config.d/*.conf
Port 44114
AuthorizedKeysFile	.ssh/authorized_keys
PasswordAuthentication no
PermitEmptyPasswords no
AllowTcpForwarding no
GatewayPorts no
X11Forwarding no
EOF

echo -e "amdgpu\nfbcon\nnouveau" >> /etc/modules
echo -e "permit persist :wheel\npermit nopass :wheel\npermit nopass night as root" >> /etc/doas.d/doas.conf
mkdir /etc/runlevels/async
rc-update add -s default async
rc-update del wpa_supplicant boot
rc-update del networking boot
rc-update add networking async
rc-update add wpa_supplicant async
echo "::once:/sbin/openrc async" >> /etc/inittab
doas mkdir /etc/acpi/LID
echo -e "#!/bin/sh\necho mem > /sys/power/state" > /etc/acpi/LID/00000080
chmod +x 00000080
rc-service acoud start
