#!/bin/sh

# settings for common commands
alias cp="cp -iv"
alias mv="mv -iv"
alias rm="rm -vI"
alias bc="bc -ql"
alias mkdir="mkdir -pv"
alias cat='bat -p'
alias cls="clear"
alias grep='grep --color=always'
alias ls='ls --color=auto'
alias ll="ls -lah"
alias l="ls -lah --color=auto"
alias tree="tree -a -I .git -I node_modules"
alias :q="exit"

# application aliases
alias v="$EDITOR"
alias vw="$EDITOR ~/.nky/Coding/Markdown/wiki/index.md"
alias vim="$EDITOR"
alias p="sudo pacman"
alias sd="shutdown now"
alias nf="neofetch"
alias cpc="clearcache"
alias rmpkg="sudo pacman -Rcns"
alias rmpkg-conf="sudo pacman -Runs"
alias pipes="pipes.sh"
alias icat="kitty +kitten icat"
alias codingsize="ncdu ~/.nky/Coding --exclude .git --exclude image --exclude node_modules --exclude jnic.zip --exclude 'Machine Learning-A-Z-Codes-Datasets.zip'"
alias foldersize="sudo du -shc"
alias findfiles="grep --exclude-dir={.mozilla,.cache,share,dump,state,node_modules,build,git,npm,autojump,cargo,gnupg} --exclude=.zcompdump -rnwinRIH . -e"
alias files="find / -type f | fzf"
alias homefiles="find ~ -type d \( -path ~/.cargo -o -path ~/.local/share -o -path ~/.local/state/nvim -o -path ~/.mozilla -o -path ~/.npm -o -path ~/.autojump -o -path ~/.cache -o -path ~/dotfiles -o -path ~/.gnupg -o -path ~/.config/zsh/zsh-syntax-highlighting -o -path ~/.config/zsh/zsh-autosuggestions -o -path ~/.config/zsh/powerlevel10k \) -prune -o -type f -not -path '*/.git/*' -not -path '*/node_modules/*' -print | fzf"
alias gitfolders="find . -type d -name '.git'"
alias convertunix="find . -type f -print0 | xargs -0 dos2unix --"
alias hst="history 1 -1 | cut -c 8- | sort | uniq | fzf | tr -d '\n' | wl-copy"
alias ncdu="ncdu --color dark -x --exclude images"
alias lf="lfrun"
alias s="sudo systemctl"

# Change directory aliases
alias .='cd ~'
alias ..='cd ..'

alias config='/usr/bin/git --git-dir=$HOME/dotfiles/ --work-tree=$HOME'
alias cad='/usr/bin/git --git-dir=$HOME/dotfiles/ --work-tree=$HOME add'
alias cco='/usr/bin/git --git-dir=$HOME/dotfiles/ --work-tree=$HOME commit -m'
alias cpu='/usr/bin/git --git-dir=$HOME/dotfiles/ --work-tree=$HOME push'
