#!/bin/sh

. "${HOME}/.config/sh/env"

if lsmod | grep -wq "pcspkr"; then
  sudo rmmod pcspkr # Remove annoying beep sound in tty
fi

if [[ "$(tty)" == "/dev/tty1" ]] then
    dwl -s startw # run dwl if not running
fi

source ~/.local/share/blesh/ble.sh

PS1='\[\e[38;5;147m\][\t] \[\e[38;5;005m\][\w] \[\e[38;5;069m\]» \[\e[0m\]'
# variables needed for command history
HISTFILE=~/.config/sh/.sh_history
HISTSIZE=10000

# push to github with the lazy way
g() {
	git add .
	git commit -m "$1"
	git push
}

lfcd() {
    tmp="$(mktemp -uq)"
    trap 'rm -f $tmp >/dev/null 2>&1 && trap - HUP INT QUIT TERM PWR EXIT' HUP INT QUIT TERM PWR EXIT
    lf -last-dir-path="$tmp" "$@"
    if [ -f "$tmp" ]; then
        dir="$(cat "$tmp")"
        [ -d "$dir" ] && [ "$dir" != "$(pwd)" ] && cd "$dir"
    fi
}

f() {
    fff "$@"
    cd "$(cat "${XDG_CACHE_HOME}/fff/.fff_d")"
}

c() {
    ccc "$@"
    cd "$(cat "${XDG_CACHE_HOME}/ccc/.ccc_d")"
}

ma() { section="$(test -z $2 && echo 0 || echo $1)" page="${2:-$1}" ; curl -s "https://man-api.ch/v1/buster/${section}/${page}" | nvimpager; }

manl() {
    man $(man -k . | awk -F'-' '{print $1}' | awk -F'(' '{ print $1 }' | sed 's/ //' | fnf)
}

webjpeg() {
    convert $1 -sampling-factor 4:2:0 -strip -quality 75 -interlace JPEG -colorspace sRGB -resize $2 $3
}

replace() {
    echo "Type the pattern you want to replace"
    read pattern
    echo "Type the phrase you want to replace with"
    read replacewith

    find . -type f -exec sed -i "s/$pattern/$replacewith/g" {} \;
}

bind -x '"\C-f":"lfcd"'
bind -x '"\C-o":"cd $(dirname $(find . -name .git -prune -o -type f | fnf))"'

source ~/.autojump/share/autojump/autojump.bash

. "${HOME}/.config/sh/aliases"
