name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.TOKEN }}
          output_action: gist
          committer_gist: ${{ secrets.GIST }}
          # Options
          user: night0721
          base: header, activity, repositories
          base_hireable: yes
          base_indepth: yes
          config_timezone: UTC
          plugin_activity: yes
          plugin_activity_skipped: stagit, night0721 
          plugin_activity_timestamps: yes
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_sections: most-used
          plugin_languages_skipped: stagit
          plugin_languages_details: percentage
          plugin_repositories: yes
          plugin_repositories_featured: cath.exe, Lilase, noted, ccc, ccc.nvim, argon, nxc-host, auth-bot
          plugin_repositories_order: featured, starred
          plugin_traffic: yes
          repositories_forks: yes
